/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quanlyraphim.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import quanlyraphim.entity.HoaDon;
import quanlyraphim.entity.DichVu;
import quanlyraphim.utils.MsgBox;
import quanlyraphim.DAO.DichVuDAO;

/**
 *
 * @author Tien
 */
public class DichVuJDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form ThucAnNuocUongJDiaLog
     */
    public DichVuJDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenCombo = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        cboMaCombo = new javax.swing.JComboBox<>();
        txtGia = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        lblMaCombo = new javax.swing.JLabel();
        txtTenCombo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTenCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenCombo.setText("Tên Combo:");

        lblGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGia.setText("Giá:");

        cboMaCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMaComboMouseClicked(evt);
            }
        });
        cboMaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaComboActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        btnNext.setText("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        lblMaCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaCombo.setText("Mã Combo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenCombo)
                            .addComponent(lblGia)
                            .addComponent(lblMaCombo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMaCombo, 0, 457, Short.MAX_VALUE)
                            .addComponent(txtGia)
                            .addComponent(txtTenCombo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaCombo)
                    .addComponent(cboMaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenCombo)
                    .addComponent(txtTenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGia)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextMouseClicked

    private void cboMaComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMaComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMaComboMouseClicked

    private void cboMaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaComboActionPerformed
        // TODO add your handling code here:
        selectComboBox();
    }//GEN-LAST:event_cboMaComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DichVuJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DichVuJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DichVuJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DichVuJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DichVuJDiaLog dialog = new DichVuJDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cboMaCombo;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblMaCombo;
    private javax.swing.JLabel lblTenCombo;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtTenCombo;
    // End of variables declaration//GEN-END:variables

    DichVuDAO dao = new DichVuDAO();
    HoaDon hd = new HoaDon();
    String tenCombo = "";
    float gia;

    void init() {
        setLocationRelativeTo(null);
        setTitle("Dịch Vụ");
        fillComboBox();
    }

    void selectComboBox() {
        DichVu dichVu = (DichVu) cboMaCombo.getSelectedItem();
        txtTenCombo.setText(dichVu.getTen());
        txtGia.setText(String.valueOf(dichVu.getGia()));
        tenCombo = dichVu.getTen();
        gia = dichVu.getGia();
//        setForm(dichVu);
    }

    void fillComboBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaCombo.getModel();
        model.removeAllElements();
        try {
            List<DichVu> list = dao.selectAll();
            for (DichVu dichVu : list) {
                model.addElement(dichVu);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu\n" + e);
        }
    }

    void next() {
        hd.setTenCombo(tenCombo);
        hd.setGiaCombo(gia);
        this.dispose();
        new ThanhToan().setVisible(true);
    }

//    void setForm(DichVu dichVu) {
//        cboMaCombo.setToolTipText(String.valueOf(dichVu.getMa()));
//        cboMaCombo.setSelectedItem(dao.selectById(dichVu.getMa()));
//        txtTenCombo.setText(dichVu.getTen());
//        txtGia.setText(String.valueOf(dichVu.getGia()));
//    }
//
//    DichVu getForm() {
//        DichVu dichVu = new DichVu();
//        dichVu.setTen(txtTenCombo.getText());
//        dichVu.setGia(Float.parseFloat(txtGia.getText()));
//        return dichVu;
//    }

}
