/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quanlyraphim.ui;

import quanlyraphim.entity.HoaDon;
import quanlyraphim.DAO.ThanhToanDAO;
import quanlyraphim.utils.XDate;

/**
 *
 * @author Tien
 */
public class HoaDonJDialog extends javax.swing.JDialog {

    ThanhToanDAO dao = new ThanhToanDAO();
    HoaDon hd = new HoaDon();

    /**
     * Creates new form HoaDonJDialog
     */
    public HoaDonJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    void init() {
        setTitle("Hóa Đơn");
        setLocationRelativeTo(null);
        HoaDon giaGhe = dao.selectByIdGiaGhe(hd.getTenGhe());
        txtTenPhim.setText(hd.getTenPhim());
        txtTenGhe.setText(hd.getTenGhe());
        txtGiaGhe.setText(String.valueOf(giaGhe));
        txtTenThucAn.setText(hd.getTenCombo());
        txtGiaThucAn.setText(String.valueOf((float) hd.getGiaCombo()));
        txtPhong.setText(hd.getMaphong());
        txtNgay.setText(String.valueOf(XDate.now()));
        float tong = (float) (hd.getGiaCombo() + hd.getGiaGhe());
        lblTien.setText(String.valueOf(tong));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnXuatHoaDon = new javax.swing.JButton();
        pnlThongTin = new javax.swing.JPanel();
        lblChonGhe = new javax.swing.JLabel();
        lblPhim = new javax.swing.JLabel();
        txtTenGhe = new javax.swing.JTextField();
        txtTenPhim = new javax.swing.JTextField();
        lblThucAn = new javax.swing.JLabel();
        txtTenThucAn = new javax.swing.JTextField();
        lblTongCong = new javax.swing.JLabel();
        lblTien = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtGiaGhe = new javax.swing.JTextField();
        lblGia = new javax.swing.JLabel();
        lblGiaThucAn = new javax.swing.JLabel();
        txtGiaThucAn = new javax.swing.JTextField();
        lblPhong = new javax.swing.JLabel();
        txtPhong = new javax.swing.JTextField();
        lblNgay = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 0));
        lblTitle.setText("Hóa Đơn");

        btnXuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        btnXuatHoaDon.setText("Xuất hóa đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        pnlThongTin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        lblChonGhe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblChonGhe.setText("Chọn Ghế");

        lblPhim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPhim.setText("Phim:");

        txtTenGhe.setEditable(false);
        txtTenGhe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenGheActionPerformed(evt);
            }
        });

        txtTenPhim.setEditable(false);
        txtTenPhim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblThucAn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThucAn.setText("Dịch vụ");

        txtTenThucAn.setEditable(false);
        txtTenThucAn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTongCong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongCong.setText("Tổng cộng:");

        lblTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTien.setText("240,000");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtGiaGhe.setEditable(false);
        txtGiaGhe.setText("140,000");
        txtGiaGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaGheActionPerformed(evt);
            }
        });

        lblGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGia.setText("Giá:");

        lblGiaThucAn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGiaThucAn.setText("Giá:");

        txtGiaThucAn.setEditable(false);
        txtGiaThucAn.setText("100,000");
        txtGiaThucAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThucAnActionPerformed(evt);
            }
        });

        lblPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPhong.setText("Mã Phòng");

        txtPhong.setEditable(false);
        txtPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNgay.setText("Ngày");

        txtNgay.setEditable(false);
        txtNgay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPhong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblThucAn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlThongTinLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenThucAn)
                                    .addComponent(txtTenGhe))))
                        .addGap(37, 37, 37)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblGiaThucAn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaThucAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhim)
                                    .addComponent(lblChonGhe)))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblNgay)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhong)
                            .addComponent(txtTenPhim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblTongCong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTien))
                            .addComponent(txtNgay))))
                .addContainerGap())
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPhim)
                .addGap(5, 5, 5)
                .addComponent(txtTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblChonGhe)
                .addGap(5, 5, 5)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTenGhe)
                        .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addComponent(lblThucAn)
                .addGap(5, 5, 5)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGiaThucAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiaThucAn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenThucAn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongCong)
                    .addComponent(lblTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(337, 337, 337))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnXuatHoaDon)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        // TODO add your handling code here:
        new ListPhim().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void txtTenGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenGheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenGheActionPerformed

    private void txtGiaGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaGheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaGheActionPerformed

    private void txtGiaThucAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThucAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThucAnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoaDonJDialog dialog = new HoaDonJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblChonGhe;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGiaThucAn;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblPhim;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblThucAn;
    private javax.swing.JLabel lblTien;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTongCong;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JTextField txtGiaGhe;
    private javax.swing.JTextField txtGiaThucAn;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtTenGhe;
    private javax.swing.JTextField txtTenPhim;
    private javax.swing.JTextField txtTenThucAn;
    // End of variables declaration//GEN-END:variables
}
