/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyraphim.ui;

import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import quanlyraphim.entity.Phim;
import quanlyraphim.utils.Auth;
import quanlyraphim.utils.MsgBox;
import quanlyraphim.utils.XDate;
import quanlyraphim.utils.XImage;
import quanlyraphim.DAO.QuanLyPhimDAO;

/**
 *
 * @author ADMIN
 */
public class QuanLyPhimJDiaLog extends javax.swing.JFrame {

//    SimpleDateFormat date_Format = new SimpleDateFormat("yyyy/MM/dd");
//    QuanLyPhimDAO dao = new QuanLyPhimDAO();
//    String strHinhAnh = null;
    /**
     * Creates new form ListPhim
     */
    public QuanLyPhimJDiaLog() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        lblTitle = new javax.swing.JLabel();
        lblMaPhim = new javax.swing.JLabel();
        txtMaPhim = new javax.swing.JTextField();
        lblTenPhim = new javax.swing.JLabel();
        txtTenPhim = new javax.swing.JTextField();
        lblNgayBD = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        lblNgayKT = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        lblHinhAnh = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLyPhim = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        lblMaTheLoai = new javax.swing.JLabel();
        txtMaTheLoai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblTitle.setText("QUẢN LÝ PHIM");

        lblMaPhim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhim.setText("Mã Phim:");

        txtMaPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhimActionPerformed(evt);
            }
        });

        lblTenPhim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenPhim.setText("Tên Phim:");

        lblNgayBD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgayBD.setText("Ngày Bắt Đầu:");

        lblNgayKT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgayKT.setText("Ngày Kết Thúc:");

        lblHinhAnh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHinhAnh.setText("HÌNH ẢNH");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(153, 51, 0));
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new-icon-16.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(153, 51, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save-icon.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 51, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-document-edit-icon-16.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 51, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblQuanLyPhim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phim:", "Tên Phim:", " Mã Thể Loại", "Ngày Bắt Đầu:", "Ngày Kết Thúc", "Hình Ảnh:"
            }
        ));
        tblQuanLyPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyPhimMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLyPhim);

        btnExit.setBackground(new java.awt.Color(153, 51, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-icon-16.png"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblMaTheLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaTheLoai.setText("Mã Thể Loại:");

        txtMaTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTheLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaTheLoai)
                    .addComponent(lblTenPhim)
                    .addComponent(lblNgayBD)
                    .addComponent(lblNgayKT)
                    .addComponent(lblMaPhim))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(txtTenPhim)
                    .addComponent(txtMaPhim, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaTheLoai)
                    .addComponent(txtNgayKT))
                .addGap(18, 18, 18)
                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaPhim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenPhim))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNgayBD)
                                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNgayKT)
                                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        insert();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked

        choosePicture();
    }//GEN-LAST:event_lblHinhAnhMouseClicked
    private void tblQuanLyPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyPhimMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tblQuanLyPhim.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblQuanLyPhimMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new quanlyraphim.ui.ListPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtMaPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhimActionPerformed

    private void txtMaTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTheLoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhimJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhimJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhimJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhimJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhimJDiaLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblMaPhim;
    private javax.swing.JLabel lblMaTheLoai;
    private javax.swing.JLabel lblNgayBD;
    private javax.swing.JLabel lblNgayKT;
    private javax.swing.JLabel lblTenPhim;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblQuanLyPhim;
    private javax.swing.JTextField txtMaPhim;
    private javax.swing.JTextField txtMaTheLoai;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtTenPhim;
    // End of variables declaration//GEN-END:variables

    QuanLyPhimDAO dao = new QuanLyPhimDAO();
    String strHinhAnh = null;
    int row = -1;

    public boolean validateForm() {
        if (txtMaPhim.getText().isEmpty() || txtTenPhim.getText().isEmpty() || txtMaTheLoai.getText().isEmpty()
                || txtNgayBD.getText().isEmpty() || txtNgayKT.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập đủ thông tin");
            return false;
        }
        return true;
    }

    void init() {
        fillTable();
        setLocationRelativeTo(null);
        setTitle("Quản Lý Phim");
    }

    void insert() {
        Phim phim = getForm();
        try {
            if (validateForm()) {
                dao.insert(phim);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Thêm thành công");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm thất bại\n" + e);
        }
    }

    void update() {
        Phim phim = getForm();
        try {
            if (validateForm()) {
                dao.update(phim);
                this.fillTable();
                MsgBox.alert(this, "Sửa thành công");
            }

        } catch (Exception e) {
            MsgBox.alert(this, "Sửa thất bại\n" + e);
        }
    }

    void delete() {
//        if (!Auth.isManager()) {
//            MsgBox.alert(this, "Bạn không được phép xóa chuyên đề");
//        } else {
        String id = txtMaPhim.getText();
        if (MsgBox.confirm(this, "Bạn muốn xóa phim này?")) {
            try {
                dao.delete(id);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xóa thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại\n" + e);
            }
        }
//        }
    }

    void choosePicture() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            fileChooser.setDialogTitle("Chọn hình ảnh");
            File file = fileChooser.getSelectedFile();
            XImage.saveLogo(file);
            ImageIcon icon = XImage.readLogo(file.getName());
            lblHinhAnh.setToolTipText(file.getName());
            lblHinhAnh.setIcon(icon);
        }
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblQuanLyPhim.getModel();
        model.setRowCount(0);
        try {
            List<Phim> list = dao.selectAll();
            for (Phim phim : list) {
                Object[] rows = {phim.getMaPhim(), phim.getTenPhim(), phim.getMaLoaiPhim(),
                    phim.getNgayBD(), phim.getNgayKT(), phim.getHinhAnh()};
                model.addRow(rows);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void edit() {
        String macd = (String) tblQuanLyPhim.getValueAt(this.row, 0);
        Phim cd = dao.selectById(macd);
        this.setForm(cd);
//        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblQuanLyPhim.getRowCount() - 1);
        txtMaPhim.setEditable(!edit);
        btnSave.setEnabled(!edit);
        btnUpdate.setEnabled(edit);
        btnDelete.setEnabled(edit);
//        //Directional state
//        btnPrev.setEnabled(edit && !first);
//        btnNext.setEnabled(edit && !last);
//        btnFirst.setEnabled(edit && !first);
//        btnLast.setEnabled(edit && !last);
    }

    void setForm(Phim phim) {
        txtMaPhim.setText(phim.getMaPhim());
        txtTenPhim.setText(phim.getTenPhim());
        txtMaTheLoai.setText(phim.getMaLoaiPhim());
        txtNgayBD.setText(XDate.toString(phim.getNgayBD(), "dd/MM/yyyy"));
        txtNgayKT.setText(XDate.toString(phim.getNgayKT(), "dd/MM/yyyy"));
        if (phim.getHinhAnh() != null) {
            lblHinhAnh.setToolTipText(phim.getHinhAnh());
            lblHinhAnh.setIcon(XImage.readLogo(phim.getHinhAnh()));
        }

    }

    Phim getForm() {
        Phim phim = new Phim();
        phim.setMaPhim(txtMaPhim.getText());
        phim.setTenPhim(txtTenPhim.getText());
        phim.setMaLoaiPhim(txtMaTheLoai.getText());
        phim.setNgayBD(XDate.toDate(txtNgayBD.getText(), "dd/MM/yyyy"));
        phim.setNgayKT(XDate.toDate(txtNgayKT.getText(), "dd/MM/yyyy"));
        phim.setHinhAnh(lblHinhAnh.getToolTipText());
        return phim;
    }

    void clearForm() {
        Phim phim = new Phim();
        lblHinhAnh.setIcon(null);
        txtNgayBD.setText("");
        txtNgayKT.setText("");
        this.setForm(phim);
        this.row = -1;
        this.updateStatus();
    }
}
