/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyraphim.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import quanlyraphim.entity.NhanVien;
import quanlyraphim.utils.Auth;
import quanlyraphim.utils.MsgBox;
import quanlyraphim.utils.XDate;
import quanlyraphim.utils.XImage;
import quanlyraphim.DAO.NhanVienDAO;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        btgVaiTro = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        lblVaiTro = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        pnlButton = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        lblMatKhau = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblSoDienThoai = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lblGioiTinh = new javax.swing.JLabel();
        rdoNhanVien = new javax.swing.JRadioButton();
        rdoQuanLy = new javax.swing.JRadioButton();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        jPhim = new javax.swing.JMenu();
        jLichChieu = new javax.swing.JMenu();
        jVe = new javax.swing.JMenu();
        jQuanLy = new javax.swing.JMenu();
        jQuanLyNhanVien = new javax.swing.JMenu();
        jQuanLyLuongNhanVien = new javax.swing.JMenu();
        jQuanLyLichChieu = new javax.swing.JMenu();
        jQuanLyPhim = new javax.swing.JMenu();
        jQuanLyPhong = new javax.swing.JMenu();
        jQuanLyLoaiVe = new javax.swing.JMenu();
        jQuanLyVe = new javax.swing.JMenu();
        jQuanLyLoaiPhim = new javax.swing.JMenu();
        jQuanLyThucAnNuocUong = new javax.swing.JMenu();
        jAbout = new javax.swing.JMenu();
        jThongKe = new javax.swing.JMenu();
        jTaiKhoan = new javax.swing.JMenu();
        jDangXuat = new javax.swing.JMenu();
        jDoiMatKhau = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 51, 0));
        lblTitle.setText("Danh Sách Nhân Viên");

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaNV.setText("Mã NV:");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setText("Tên NV:");

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoDienThoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblVaiTro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVaiTro.setText("Vai trò:");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Mật Khẩu", "Ngày Sinh", "Địa Chỉ", "Số Điện Thoại", "Giới Tính", "Vai Trò"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMatKhau.setText("Mật Khẩu:");

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgaySinh.setText("Ngày Sinh:");

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiaChi.setText("Địa Chỉ:");

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoDienThoai.setText("Số Điện Thoại:");

        btgGioiTinh.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        btgGioiTinh.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoNu.setText("Nữ");

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGioiTinh.setText("Giới tính:");

        btgVaiTro.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoNhanVien.setSelected(true);
        rdoNhanVien.setText("Nhân Viên");

        btgVaiTro.add(rdoQuanLy);
        rdoQuanLy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoQuanLy.setText("Quản lý");

        btnNew.setBackground(new java.awt.Color(153, 51, 0));
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new-icon-16.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(153, 51, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-document-edit-icon-16.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(153, 51, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save-icon.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 51, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-movies.gif"))); // NOI18N
        jPhim.setText("Phim");
        jPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPhimMouseClicked(evt);
            }
        });
        jPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhimActionPerformed(evt);
            }
        });
        Menu.add(jPhim);

        jLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-movie-30.png"))); // NOI18N
        jLichChieu.setText("Lịch Chiếu");
        jLichChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLichChieuMouseClicked(evt);
            }
        });
        Menu.add(jLichChieu);

        jVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cinema-ticket-30.png"))); // NOI18N
        jVe.setText("Vé");
        jVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVeMouseClicked(evt);
            }
        });
        Menu.add(jVe);

        jQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-operating-system-30.png"))); // NOI18N
        jQuanLy.setText("Quản Lý");
        jQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyMouseClicked(evt);
            }
        });

        jQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Person-Male-Light-icon-16.png"))); // NOI18N
        jQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        jQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyNhanVienMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyNhanVien);

        jQuanLyLuongNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-document-edit-icon-16.png"))); // NOI18N
        jQuanLyLuongNhanVien.setText("Quản Lý Lương");
        jQuanLyLuongNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLuongNhanVienMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLuongNhanVien);

        jQuanLyLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lc.png"))); // NOI18N
        jQuanLyLichChieu.setText(" Quản Lý Lịch Chiếu");
        jQuanLyLichChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLichChieuMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLichChieu);

        jQuanLyPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phim.png"))); // NOI18N
        jQuanLyPhim.setText("Quản Lý Phim");
        jQuanLyPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyPhimMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyPhim);

        jQuanLyPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phong.png"))); // NOI18N
        jQuanLyPhong.setText(" Quản Lý Phòng");
        jQuanLyPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyPhongMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyPhong);

        jQuanLyLoaiVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loaive.png"))); // NOI18N
        jQuanLyLoaiVe.setText("Quản Lý Loại Vé");
        jQuanLyLoaiVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLoaiVeMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLoaiVe);

        jQuanLyVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ve.png"))); // NOI18N
        jQuanLyVe.setText("Quản Lý Vé");
        jQuanLyVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyVeMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyVe);

        jQuanLyLoaiPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loaiphim.png"))); // NOI18N
        jQuanLyLoaiPhim.setText("Quản Lý Loại Phim");
        jQuanLyLoaiPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLoaiPhimMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLoaiPhim);

        jQuanLyThucAnNuocUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thucannuocuong.png"))); // NOI18N
        jQuanLyThucAnNuocUong.setText("Quản Lý Dịch Vụ");
        jQuanLyThucAnNuocUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyThucAnNuocUongMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyThucAnNuocUong);

        Menu.add(jQuanLy);

        jAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-30.png"))); // NOI18N
        jAbout.setText("About");
        jAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAboutMouseClicked(evt);
            }
        });
        Menu.add(jAbout);

        jThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doanhthu.png"))); // NOI18N
        jThongKe.setText("Doanh Thu");
        jThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jThongKeMouseClicked(evt);
            }
        });
        Menu.add(jThongKe);

        jTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jTaiKhoan.setText("Tài Khoản");
        jTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaiKhoanMouseClicked(evt);
            }
        });

        jDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dX.png"))); // NOI18N
        jDangXuat.setText("Đăng Xuất");
        jDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDangXuatMouseClicked(evt);
            }
        });
        jDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDangXuatActionPerformed(evt);
            }
        });
        jTaiKhoan.add(jDangXuat);

        jDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jDoiMatKhau.setText("Đổi Mật Khẩu");
        jDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDoiMatKhauMouseClicked(evt);
            }
        });
        jDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoiMatKhauActionPerformed(evt);
            }
        });
        jTaiKhoan.add(jDoiMatKhau);

        Menu.add(jTaiKhoan);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblVaiTro)
                        .addGap(18, 18, 18)
                        .addComponent(rdoNhanVien)
                        .addGap(19, 19, 19)
                        .addComponent(rdoQuanLy))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMaNV)
                                    .addComponent(lblTenNV))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoNam)
                                .addGap(55, 55, 55)
                                .addComponent(rdoNu)))))
                .addGap(47, 47, 47)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblMaNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTenNV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblTitle)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMatKhau))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNgaySinh))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiaChi))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoDienThoai))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rdoNam)
                                        .addComponent(lblGioiTinh))
                                    .addComponent(rdoNu)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoNhanVien)
                        .addComponent(lblVaiTro))
                    .addComponent(rdoQuanLy))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        insert();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        update();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tblNhanVien.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void jPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPhimMouseClicked
        // TODO add your handling code here:
        new ListPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPhimMouseClicked

    private void jPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhimActionPerformed

    private void jLichChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLichChieuMouseClicked
        // TODO add your handling code here:
        new LichChieuPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLichChieuMouseClicked

    private void jVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVeMouseClicked
        // TODO add your handling code here:
        new QuanLyVe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jVeMouseClicked

    private void jQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyNhanVienMouseClicked
        // TODO add your handling code here:
        new QuanLyNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyNhanVienMouseClicked

    private void jQuanLyLuongNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLuongNhanVienMouseClicked
        // TODO add your handling code here:
        new QuanLyLuongJDialog().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLuongNhanVienMouseClicked

    private void jQuanLyLichChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLichChieuMouseClicked
        // TODO add your handling code here:
        new LichChieuPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLichChieuMouseClicked

    private void jQuanLyPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyPhimMouseClicked
        // TODO add your handling code here:
        new QuanLyPhimJDiaLog().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyPhimMouseClicked

    private void jQuanLyPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyPhongMouseClicked
        // TODO add your handling code here:
        new QuanLyPhongJDialog(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyPhongMouseClicked

    private void jQuanLyLoaiVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLoaiVeMouseClicked
        // TODO add your handling code here:
        new QuanLyLoaiVeJDialog(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLoaiVeMouseClicked

    private void jQuanLyVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyVeMouseClicked
        // TODO add your handling code here:
        new QuanLyVe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyVeMouseClicked

    private void jQuanLyLoaiPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLoaiPhimMouseClicked
        // TODO add your handling code here:
        new QuanLyLoaiPhimJDialog(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLoaiPhimMouseClicked

    private void jQuanLyThucAnNuocUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyThucAnNuocUongMouseClicked
        // TODO add your handling code here:
        new QuanLyDichVuJDialog(this, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_jQuanLyThucAnNuocUongMouseClicked

    private void jQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyMouseClicked
        // TODO add your handling code here:
        check();
    }//GEN-LAST:event_jQuanLyMouseClicked

    private void jAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAboutMouseClicked
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_jAboutMouseClicked

    private void jThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jThongKeMouseClicked
        // TODO add your handling code here:
        new DoanhThu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jThongKeMouseClicked

    private void jDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDangXuatMouseClicked
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jDangXuatMouseClicked

    private void jDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDangXuatActionPerformed

    private void jDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDoiMatKhauMouseClicked
        // TODO add your handling code here:
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jDoiMatKhauMouseClicked

    private void jDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoiMatKhauActionPerformed

    private void jTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaiKhoanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaiKhoanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.ButtonGroup btgVaiTro;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenu jAbout;
    private javax.swing.JMenu jDangXuat;
    private javax.swing.JMenu jDoiMatKhau;
    private javax.swing.JMenu jLichChieu;
    private javax.swing.JMenu jPhim;
    private javax.swing.JMenu jQuanLy;
    private javax.swing.JMenu jQuanLyLichChieu;
    private javax.swing.JMenu jQuanLyLoaiPhim;
    private javax.swing.JMenu jQuanLyLoaiVe;
    private javax.swing.JMenu jQuanLyLuongNhanVien;
    private javax.swing.JMenu jQuanLyNhanVien;
    private javax.swing.JMenu jQuanLyPhim;
    private javax.swing.JMenu jQuanLyPhong;
    private javax.swing.JMenu jQuanLyThucAnNuocUong;
    private javax.swing.JMenu jQuanLyVe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jTaiKhoan;
    private javax.swing.JMenu jThongKe;
    private javax.swing.JMenu jVe;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables

    NhanVienDAO dao = new NhanVienDAO();
    int row = -1;

    void check() {
        if (Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền truy cập vào chức năng này !");
            jQuanLy.setEnabled(false);
        }
    }

    void init() {
//        setIconImage(XImage.getAppIcon());
        setTitle("Quản lý nhân viên");
        setLocationRelativeTo(null); // đưa cửa sổ ra giữa màn hình
        this.fillTable(); // đổ dữ liệu nhân viên vào bảng
        this.updateStatus(); // cập nhật trạng thái form
    }

    public boolean checkValidateForm() {
        if (txtMaNV.getText().isEmpty() || txtTenNV.getText().isEmpty() || txtMatKhau.getText().isEmpty()
                || txtDiaChi.getText().isEmpty() || txtNgaySinh.getText().isEmpty() || txtSoDienThoai.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập đủ thông tin");
            return false;
        }
        return true;
    }
    int ranNum = (int) (Math.random() * 1000000000);

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> list = dao.selectAll();
            for (NhanVien nv : list) {
                Object[] row = {
                    nv.getMaNV(),
                    nv.getTenNV(),
                    nv.getMatKhau() + ranNum,
                    nv.getNgaySinh(),
                    nv.getDiaChi(),
                    nv.getSoDT(),
                    nv.getGioiTinh(),
                    nv.getVaiTro()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void insert() {
        NhanVien nv = this.getForm();
        try {
            if (checkValidateForm()) {
                dao.insert(nv); // thêm mới
                this.fillTable(); // đỗ lại bảng
                this.clearForm(); // xóa trắng form
                MsgBox.alert(this, "Thêm mới thành công!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!\n" + e);
        }
    }

    void update() {
        NhanVien nv = this.getForm();
        try {
//                if (!Auth.isManager()) {
//                    rdoTruongPhong.isEnabled();
//                    MsgBox.alert(this, "Bạn không thể sửa");
//                    return;
//                }
            if (checkValidateForm()) {
                dao.update(nv); // cập nhật
                this.fillTable(); // đổ lại bảng
                this.clearForm();
                MsgBox.alert(this, "Cập nhật thành công!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    void delete() {
//        if (!Auth.isManager()) {
//            MsgBox.alert(this, "Bạn không có quyền xóa nhân viên!");
//        } else {
        String manv = txtMaNV.getText();
        if (manv.equals(Auth.user.getMaNV())) {
            MsgBox.alert(this, "Bạn không được xóa chính bạn!");
        } else if (MsgBox.confirm(this, "Bạn thực sự muốn xóa nhân viên này?")) {
            try {
                dao.delete(manv);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại!");
            }
        }
    }
//    }

    void clearForm() {
        NhanVien nv = new NhanVien();
        this.setForm(nv);
        this.row = -1;
        this.updateStatus();
        txtNgaySinh.setText("");
        rdoNam.setSelected(true);
        rdoNhanVien.setSelected(true);
    }

    void edit() {
        String manv = (String) tblNhanVien.getValueAt(this.row, 0);
        NhanVien nv = dao.selectById(manv);
        this.setForm(nv);
        this.updateStatus();

    }

    void setForm(NhanVien nv) {
        txtMaNV.setText(nv.getMaNV());
        txtTenNV.setText(nv.getTenNV());
        txtMatKhau.setText(nv.getMatKhau());
        txtNgaySinh.setText(XDate.toString(nv.getNgaySinh(), "dd/MM/yyyy"));
        txtSoDienThoai.setText(nv.getSoDT());
        txtDiaChi.setText(nv.getDiaChi());
        String gioiTinh = nv.getGioiTinh();
        if (gioiTinh != null && gioiTinh.equalsIgnoreCase("Nam")) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
//        } else if (gioiTinh != null && gioiTinh.equals("Nữ")) {
//            rdoNu.setSelected(true);
//        } 
        String vaitro = nv.getVaiTro();
        if (vaitro != null && vaitro.equalsIgnoreCase("Nhân viên")) {
            rdoNhanVien.setSelected(true);
        } else {
            rdoQuanLy.setSelected(true);
        }
//        } else if (vaitro != null && vaitro.equals("Nhân viên")) {
//            rdoNhanVien.setSelected(true);
//        }
    }

    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setTenNV(txtTenNV.getText());
        nv.setMatKhau(txtMatKhau.getText());
        nv.setNgaySinh(XDate.toDate(txtNgaySinh.getText(), "dd/MM/yyyy"));
        nv.setSoDT(txtSoDienThoai.getText());
        nv.setDiaChi(txtDiaChi.getText());
        if (rdoNam.isSelected()) {
            nv.setGioiTinh("Nam");
        } else {
            nv.setGioiTinh("Nữ");
        }
//        } else if (rdoNu.isSelected()) {
//            nv.setGioiTinh("Nữ");
//        }
        if (rdoNhanVien.isSelected()) {
            nv.setVaiTro("Nhân viên");
        } else {
            nv.setVaiTro("Quản lý");
        }
//        } else if (rdoQuanLy.isSelected()) {
//            nv.setVaiTro("Quản lý");
//        }
        return nv;
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblNhanVien.getRowCount() - 1);
        // Trạng thái form
        txtMaNV.setEditable(!edit);
        btnSave.setEnabled(!edit);
        btnEdit.setEnabled(edit);
        btnDelete.setEnabled(edit);
//        
//        // Trạng thái điều hướng
//        btnFirst.setEnabled(edit && !first);
//        btnPrev.setEnabled(edit && !first);
//        btnNext.setEnabled(edit && !last);
//        btnLast.setEnabled(edit && !last);
    }
}
