/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyraphim.ui;

import javax.swing.JOptionPane;
import quanlyraphim.entity.HoaDon;
import quanlyraphim.utils.Auth;
import quanlyraphim.utils.MsgBox;
import quanlyraphim.DAO.ThanhToanDAO;
import quanlyraphim.utils.XDate;

/**
 *
 * @author Admin
 */
public class ThanhToan extends javax.swing.JFrame {

    HoaDon hd = new HoaDon();
    ThanhToanDAO dao = new ThanhToanDAO();

    /**
     * Creates new form HoaDon
     */
    public ThanhToan() {
        initComponents();
        init();
    }

    Boolean checkThongKe() {
        if (Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền truy cập vào chức năng này !");
            jQuanLy.setEnabled(false);
            return false;
        }
        return true;
    }

    void init() {
        setLocationRelativeTo(null);
        setTitle("Thanh Toán");
        HoaDon giaGhe = dao.selectByIdGiaGhe(hd.getTenGhe());
        txtTenPhim.setText(hd.getTenPhim());
        txtTenGhe.setText(hd.getTenGhe());
        txtGiaGhe.setText(String.valueOf(giaGhe));
        txtTenThucAn.setText(hd.getTenCombo());
        txtGiaThucAn.setText(String.valueOf((float) hd.getGiaCombo()));
        txtPhong.setText(hd.getMaphong());
        txtNgay.setText(String.valueOf(XDate.now()));
        float tong = (float) (hd.getGiaCombo() + hd.getGiaGhe());
        lblTien.setText(String.valueOf(tong));
    }

    void insert() {
        HoaDon hd = new HoaDon();
        try {
            dao.insert(hd);
        } catch (Exception e) {
        }
    }

    void check() {
        if (Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền truy cập vào chức năng này !");
            jQuanLy.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        pnlThongTin = new javax.swing.JPanel();
        lblChonGhe = new javax.swing.JLabel();
        lblPhim = new javax.swing.JLabel();
        txtTenGhe = new javax.swing.JTextField();
        txtTenPhim = new javax.swing.JTextField();
        lblThucAn = new javax.swing.JLabel();
        txtTenThucAn = new javax.swing.JTextField();
        lblTongCong = new javax.swing.JLabel();
        lblTien = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtGiaGhe = new javax.swing.JTextField();
        lblGia = new javax.swing.JLabel();
        lblGiaThucAn = new javax.swing.JLabel();
        txtGiaThucAn = new javax.swing.JTextField();
        lblPhong = new javax.swing.JLabel();
        txtPhong = new javax.swing.JTextField();
        lblNgay = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        pnlThanhToan = new javax.swing.JPanel();
        txtNhap = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btnMomo = new javax.swing.JButton();
        btnThanhToanVND = new javax.swing.JButton();
        btnBankingQR = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        jPhim = new javax.swing.JMenu();
        jLichChieu = new javax.swing.JMenu();
        jVe = new javax.swing.JMenu();
        jQuanLy = new javax.swing.JMenu();
        jQuanLyNhanVien = new javax.swing.JMenu();
        jQuanLyLuongNhanVien = new javax.swing.JMenu();
        jQuanLyLichChieu = new javax.swing.JMenu();
        jQuanLyPhim = new javax.swing.JMenu();
        jQuanLyPhong = new javax.swing.JMenu();
        jQuanLyLoaiVe = new javax.swing.JMenu();
        jQuanLyVe = new javax.swing.JMenu();
        jQuanLyLoaiPhim = new javax.swing.JMenu();
        jQuanLyThucAnNuocUong = new javax.swing.JMenu();
        jAbout = new javax.swing.JMenu();
        jThongKe = new javax.swing.JMenu();
        jTaiKhoan = new javax.swing.JMenu();
        jDangXuat = new javax.swing.JMenu();
        jDoiMatKhau = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 51, 0));
        lblTitle.setText("Thanh Toán");

        pnlThongTin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        lblChonGhe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblChonGhe.setText("Chọn Ghế");

        lblPhim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPhim.setText("Phim:");

        txtTenGhe.setEditable(false);
        txtTenGhe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenGheActionPerformed(evt);
            }
        });

        txtTenPhim.setEditable(false);
        txtTenPhim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblThucAn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThucAn.setText("Dịch vụ");

        txtTenThucAn.setEditable(false);
        txtTenThucAn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTongCong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongCong.setText("Tổng cộng:");

        lblTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTien.setText("240,000");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtGiaGhe.setEditable(false);
        txtGiaGhe.setText("140,000");
        txtGiaGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaGheActionPerformed(evt);
            }
        });

        lblGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGia.setText("Giá:");

        lblGiaThucAn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGiaThucAn.setText("Giá:");

        txtGiaThucAn.setEditable(false);
        txtGiaThucAn.setText("100,000");
        txtGiaThucAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThucAnActionPerformed(evt);
            }
        });

        lblPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPhong.setText("Mã Phòng");

        txtPhong.setEditable(false);
        txtPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNgay.setText("Ngày");

        txtNgay.setEditable(false);
        txtNgay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPhong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblThucAn)
                                .addGap(0, 148, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlThongTinLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenThucAn)
                                    .addComponent(txtTenGhe))))
                        .addGap(37, 37, 37)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblGiaThucAn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaThucAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhim)
                                    .addComponent(lblChonGhe)))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblNgay)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhong)
                            .addComponent(txtTenPhim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblTongCong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTien))
                            .addComponent(txtNgay))))
                .addContainerGap())
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPhim)
                .addGap(5, 5, 5)
                .addComponent(txtTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblChonGhe)
                .addGap(5, 5, 5)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiaGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTenGhe)
                        .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addComponent(lblThucAn)
                .addGap(5, 5, 5)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGiaThucAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiaThucAn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenThucAn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPhong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongCong)
                    .addComponent(lblTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlThanhToan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("1");

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 51, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("3");

        jButton5.setBackground(new java.awt.Color(153, 51, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("4");

        jButton6.setBackground(new java.awt.Color(153, 51, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 51, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("6");

        jButton9.setBackground(new java.awt.Color(153, 51, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("7");

        jButton11.setBackground(new java.awt.Color(153, 51, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("9");

        jButton12.setBackground(new java.awt.Color(153, 51, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Xóa");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(153, 51, 0));
        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("8");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(153, 51, 0));
        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));

        btnMomo.setBackground(new java.awt.Color(153, 51, 0));
        btnMomo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMomo.setForeground(new java.awt.Color(255, 255, 255));
        btnMomo.setText("Mo Mo");
        btnMomo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMomoMouseClicked(evt);
            }
        });
        btnMomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMomoActionPerformed(evt);
            }
        });

        btnThanhToanVND.setBackground(new java.awt.Color(153, 51, 0));
        btnThanhToanVND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThanhToanVND.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToanVND.setText("Thanh Toán VND");
        btnThanhToanVND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanVNDActionPerformed(evt);
            }
        });

        btnBankingQR.setBackground(new java.awt.Color(153, 51, 0));
        btnBankingQR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBankingQR.setForeground(new java.awt.Color(255, 255, 255));
        btnBankingQR.setText("Bankinng QRcode");
        btnBankingQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankingQRActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 51, 0));
        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("0");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThanhToanLayout = new javax.swing.GroupLayout(pnlThanhToan);
        pnlThanhToan.setLayout(pnlThanhToanLayout);
        pnlThanhToanLayout.setHorizontalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanhToanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThanhToanVND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBankingQR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(btnMomo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNhap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThanhToanLayout.createSequentialGroup()
                        .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        pnlThanhToanLayout.setVerticalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanhToanLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton13)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addComponent(jButton15))
                .addGap(80, 80, 80)
                .addComponent(btnThanhToanVND)
                .addGap(18, 18, 18)
                .addComponent(btnBankingQR)
                .addGap(18, 18, 18)
                .addComponent(btnMomo)
                .addGap(18, 18, 18))
        );

        jPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-movies.gif"))); // NOI18N
        jPhim.setText("Phim");
        jPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPhimMouseClicked(evt);
            }
        });
        jPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhimActionPerformed(evt);
            }
        });
        Menu.add(jPhim);

        jLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-movie-30.png"))); // NOI18N
        jLichChieu.setText("Lịch Chiếu");
        jLichChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLichChieuMouseClicked(evt);
            }
        });
        Menu.add(jLichChieu);

        jVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cinema-ticket-30.png"))); // NOI18N
        jVe.setText("Vé");
        jVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVeMouseClicked(evt);
            }
        });
        Menu.add(jVe);

        jQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-operating-system-30.png"))); // NOI18N
        jQuanLy.setText("Quản Lý");
        jQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyMouseClicked(evt);
            }
        });

        jQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Person-Male-Light-icon-16.png"))); // NOI18N
        jQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        jQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyNhanVienMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyNhanVien);

        jQuanLyLuongNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-document-edit-icon-16.png"))); // NOI18N
        jQuanLyLuongNhanVien.setText("Quản Lý Lương");
        jQuanLyLuongNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLuongNhanVienMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLuongNhanVien);

        jQuanLyLichChieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lc.png"))); // NOI18N
        jQuanLyLichChieu.setText(" Quản Lý Lịch Chiếu");
        jQuanLyLichChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLichChieuMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLichChieu);

        jQuanLyPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phim.png"))); // NOI18N
        jQuanLyPhim.setText("Quản Lý Phim");
        jQuanLyPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyPhimMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyPhim);

        jQuanLyPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phong.png"))); // NOI18N
        jQuanLyPhong.setText(" Quản Lý Phòng");
        jQuanLyPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyPhongMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyPhong);

        jQuanLyLoaiVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loaive.png"))); // NOI18N
        jQuanLyLoaiVe.setText("Quản Lý Loại Vé");
        jQuanLyLoaiVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLoaiVeMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLoaiVe);

        jQuanLyVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ve.png"))); // NOI18N
        jQuanLyVe.setText("Quản Lý Vé");
        jQuanLyVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyVeMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyVe);

        jQuanLyLoaiPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loaiphim.png"))); // NOI18N
        jQuanLyLoaiPhim.setText("Quản Lý Loại Phim");
        jQuanLyLoaiPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyLoaiPhimMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyLoaiPhim);

        jQuanLyThucAnNuocUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thucannuocuong.png"))); // NOI18N
        jQuanLyThucAnNuocUong.setText("Quản Lý Dịch Vụ");
        jQuanLyThucAnNuocUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuanLyThucAnNuocUongMouseClicked(evt);
            }
        });
        jQuanLy.add(jQuanLyThucAnNuocUong);

        Menu.add(jQuanLy);

        jAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-30.png"))); // NOI18N
        jAbout.setText("About");
        jAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAboutMouseClicked(evt);
            }
        });
        Menu.add(jAbout);

        jThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doanhthu.png"))); // NOI18N
        jThongKe.setText("Doanh Thu");
        jThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jThongKeMouseClicked(evt);
            }
        });
        Menu.add(jThongKe);

        jTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jTaiKhoan.setText("Tài Khoản");
        jTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaiKhoanMouseClicked(evt);
            }
        });

        jDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dX.png"))); // NOI18N
        jDangXuat.setText("Đăng Xuất");
        jDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDangXuatMouseClicked(evt);
            }
        });
        jDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDangXuatActionPerformed(evt);
            }
        });
        jTaiKhoan.add(jDangXuat);

        jDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        jDoiMatKhau.setText("Đổi Mật Khẩu");
        jDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDoiMatKhauMouseClicked(evt);
            }
        });
        jDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoiMatKhauActionPerformed(evt);
            }
        });
        jTaiKhoan.add(jDoiMatKhau);

        Menu.add(jTaiKhoan);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiaGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaGheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaGheActionPerformed

    private void txtGiaThucAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThucAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThucAnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnThanhToanVNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanVNDActionPerformed
        // TODO add your handling code here:
        insert();
        JOptionPane.showConfirmDialog(this, "Xác nhận thanh toán");
        new HoaDonJDialog(this, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThanhToanVNDActionPerformed

    private void btnBankingQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankingQRActionPerformed
        // TODO add your handling code here:
        insert();
        JOptionPane.showConfirmDialog(this, "Xác nhận thanh toán");
        new HoaDonJDialog(this, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBankingQRActionPerformed

    private void btnMomoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMomoMouseClicked
        // TODO add your handling code here:
        insert();
        JOptionPane.showConfirmDialog(this, "Xác nhận thanh toán");
        new HoaDonJDialog(this, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMomoMouseClicked

    private void btnMomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMomoActionPerformed
        // TODO add your handling code here:
        insert();
        JOptionPane.showConfirmDialog(this, "Xác nhận thanh toán");
        new HoaDonJDialog(this, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMomoActionPerformed

    private void txtTenGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenGheActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTenGheActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPhimMouseClicked
        // TODO add your handling code here:
        new ListPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPhimMouseClicked

    private void jPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhimActionPerformed

    private void jLichChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLichChieuMouseClicked
        // TODO add your handling code here:
        new LichChieuPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLichChieuMouseClicked

    private void jVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVeMouseClicked
        // TODO add your handling code here:
        new QuanLyVe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jVeMouseClicked

    private void jQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyNhanVienMouseClicked
        // TODO add your handling code here:
        new QuanLyNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyNhanVienMouseClicked

    private void jQuanLyLuongNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLuongNhanVienMouseClicked
        // TODO add your handling code here:
        new QuanLyLuongJDialog().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLuongNhanVienMouseClicked

    private void jQuanLyLichChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLichChieuMouseClicked
        // TODO add your handling code here:
        new LichChieuPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLichChieuMouseClicked

    private void jQuanLyPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyPhimMouseClicked
        // TODO add your handling code here:
        new ListPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyPhimMouseClicked

    private void jQuanLyPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyPhongMouseClicked
        // TODO add your handling code here:
        new QuanLyPhongJDialog(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyPhongMouseClicked

    private void jQuanLyLoaiVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLoaiVeMouseClicked
        // TODO add your handling code here:
        new QuanLyLoaiVeJDialog(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLoaiVeMouseClicked

    private void jQuanLyVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyVeMouseClicked
        // TODO add your handling code here:
        new QuanLyVe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyVeMouseClicked

    private void jQuanLyLoaiPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyLoaiPhimMouseClicked
        // TODO add your handling code here:
        new QuanLyLoaiPhimJDialog(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jQuanLyLoaiPhimMouseClicked

    private void jQuanLyThucAnNuocUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyThucAnNuocUongMouseClicked
        // TODO add your handling code here:
        new QuanLyDichVuJDialog(this, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_jQuanLyThucAnNuocUongMouseClicked

    private void jQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuanLyMouseClicked
        // TODO add your handling code here:
        check();
    }//GEN-LAST:event_jQuanLyMouseClicked

    private void jAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAboutMouseClicked
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_jAboutMouseClicked

    private void jThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jThongKeMouseClicked
        // TODO add your handling code here:
        if (checkThongKe()) {
            new DoanhThu().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jThongKeMouseClicked

    private void jDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDangXuatMouseClicked
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jDangXuatMouseClicked

    private void jDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDangXuatActionPerformed

    private void jDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDoiMatKhauMouseClicked
        // TODO add your handling code here:
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jDoiMatKhauMouseClicked

    private void jDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoiMatKhauActionPerformed

    private void jTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaiKhoanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaiKhoanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton btnBankingQR;
    private javax.swing.JButton btnMomo;
    private javax.swing.JButton btnThanhToanVND;
    private javax.swing.JMenu jAbout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jDangXuat;
    private javax.swing.JMenu jDoiMatKhau;
    private javax.swing.JMenu jLichChieu;
    private javax.swing.JMenu jPhim;
    private javax.swing.JMenu jQuanLy;
    private javax.swing.JMenu jQuanLyLichChieu;
    private javax.swing.JMenu jQuanLyLoaiPhim;
    private javax.swing.JMenu jQuanLyLoaiVe;
    private javax.swing.JMenu jQuanLyLuongNhanVien;
    private javax.swing.JMenu jQuanLyNhanVien;
    private javax.swing.JMenu jQuanLyPhim;
    private javax.swing.JMenu jQuanLyPhong;
    private javax.swing.JMenu jQuanLyThucAnNuocUong;
    private javax.swing.JMenu jQuanLyVe;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu jTaiKhoan;
    private javax.swing.JMenu jThongKe;
    private javax.swing.JMenu jVe;
    private javax.swing.JLabel lblChonGhe;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGiaThucAn;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblPhim;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblThucAn;
    private javax.swing.JLabel lblTien;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTongCong;
    private javax.swing.JPanel pnlThanhToan;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JTextField txtGiaGhe;
    private javax.swing.JTextField txtGiaThucAn;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtNhap;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtTenGhe;
    private javax.swing.JTextField txtTenPhim;
    private javax.swing.JTextField txtTenThucAn;
    // End of variables declaration//GEN-END:variables
}
