/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyraphim.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlyraphim.entity.HoaDon;
import quanlyraphim.entity.LichChieu;
import quanlyraphim.utils.MsgBox;
import quanlyraphim.utils.XDate;
import quanlyraphim.DAO.LichChieuDAO;

/**
 *
 * @author ADMIN
 */
public class viewPhim extends javax.swing.JFrame {

    /**
     * Creates new form viewPhim
     */
    public viewPhim() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblViewPhim = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblMaLichChieu = new javax.swing.JLabel();
        txtMaLichChieu = new javax.swing.JTextField();
        lblMaPhong = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        lblMaPhim = new javax.swing.JLabel();
        txtMaPhim = new javax.swing.JTextField();
        txtGioChieu = new javax.swing.JTextField();
        lblGioChieu = new javax.swing.JLabel();
        txtNgayChieu = new javax.swing.JTextField();
        lblNgayChieu = new javax.swing.JLabel();
        pnlTimKiem = new javax.swing.JPanel();
        lblFindMaLichChieu = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        lblTenPhim = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblViewPhim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblViewPhim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Lịch Chiếu", "Mã Phòng", "Giờ Chiếu", "Ngày Chiếu"
            }
        ));
        tblViewPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewPhimMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblViewPhim);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 51, 0));
        lblTitle.setText("Lịch Chiếu");

        lblMaLichChieu.setText("Mã Lịch Chiếu:");

        txtMaLichChieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaLichChieu.setForeground(new java.awt.Color(255, 51, 51));

        lblMaPhong.setText("Mã Phòng:");

        txtMaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaPhong.setForeground(new java.awt.Color(255, 51, 51));

        lblMaPhim.setText("Mã Phim:");

        txtMaPhim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaPhim.setForeground(new java.awt.Color(255, 51, 51));

        txtGioChieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGioChieu.setForeground(new java.awt.Color(255, 51, 51));

        lblGioChieu.setText("Giờ Chiếu:");

        txtNgayChieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNgayChieu.setForeground(new java.awt.Color(255, 51, 51));

        lblNgayChieu.setText("Ngày Chiếu:");

        pnlTimKiem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFindMaLichChieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFindMaLichChieu.setText("Xin mời nhập mã lịch chiếu:");

        txtFind.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFind.setForeground(new java.awt.Color(255, 51, 51));
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });

        btnFind.setBackground(new java.awt.Color(153, 51, 0));
        btnFind.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFind.setForeground(new java.awt.Color(255, 255, 255));
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-icon-24.png"))); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lblTenPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTenPhim.setText("Bố Già");

        javax.swing.GroupLayout pnlTimKiemLayout = new javax.swing.GroupLayout(pnlTimKiem);
        pnlTimKiem.setLayout(pnlTimKiemLayout);
        pnlTimKiemLayout.setHorizontalGroup(
            pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemLayout.createSequentialGroup()
                .addGroup(pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTimKiemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtFind)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTimKiemLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(lblFindMaLichChieu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlTimKiemLayout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(lblTenPhim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemLayout.setVerticalGroup(
            pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFindMaLichChieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenPhim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNext.setBackground(new java.awt.Color(153, 51, 0));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login-icon-16.png"))); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 51, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-icon-16.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMaLichChieu)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaLichChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMaPhim)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMaPhong)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblGioChieu)
                                .addGap(18, 18, 18)
                                .addComponent(txtGioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNgayChieu)
                                .addGap(18, 18, 18)
                                .addComponent(txtNgayChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 460, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(pnlTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLichChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaLichChieu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaPhim))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaPhong))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGioChieu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgayChieu))
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        find();
    }//GEN-LAST:event_btnFindActionPerformed

    private void tblViewPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewPhimMouseClicked
        // TODO add your handling code here:   
        if (evt.getClickCount() == 1) {
            this.row = tblViewPhim.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblViewPhimMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        new ChonGhe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new ListPhim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPhim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFindMaLichChieu;
    private javax.swing.JLabel lblGioChieu;
    private javax.swing.JLabel lblMaLichChieu;
    private javax.swing.JLabel lblMaPhim;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblNgayChieu;
    private javax.swing.JLabel lblTenPhim;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlTimKiem;
    private javax.swing.JTable tblViewPhim;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtGioChieu;
    private javax.swing.JTextField txtMaLichChieu;
    private javax.swing.JTextField txtMaPhim;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtNgayChieu;
    // End of variables declaration//GEN-END:variables

    LichChieuDAO dao = new LichChieuDAO();
    HoaDon hd = new HoaDon();
    int row = -1;
    String maPhim = hd.getMaPhim();

    void init() {
        txtMaPhim.setText(hd.getMaPhim());
        fillTable();
        setLocationRelativeTo(null);
        setTitle("LICH CHIEU");
        txtGioChieu.setEditable(false);
        txtMaLichChieu.setEditable(false);
        txtMaPhim.setEditable(true);
        txtMaPhong.setEditable(false);
        txtNgayChieu.setEditable(false);
        lblTenPhim.setText(hd.getTenPhim());
    }

    void edit() {
        String malc = (String) tblViewPhim.getValueAt(this.row, 0);
        LichChieu lc = dao.selectById(malc);
        this.setForm(lc);
//        tabs.setSelectedIndex(0);
//        this.updateStatus();
    }

    void setForm(LichChieu lc) {
        txtMaLichChieu.setText(lc.getMaLichChieu());
        txtMaPhong.setText(lc.getMaPhong());
        txtGioChieu.setText(lc.getGioChieu());
        txtNgayChieu.setText(XDate.toString(lc.getNgayChieu(), "dd/MM/yyyy"));
        hd.setMaphong(lc.getMaPhong());
    }

    LichChieu getForm() {
        LichChieu lc = new LichChieu();
        lc.setMaLichChieu(txtMaLichChieu.getText());
        lc.setMaPhong(txtMaPhong.getText());
        lc.setGioChieu(txtGioChieu.getText());
        lc.setNgayChieu(XDate.toDate(txtNgayChieu.getText(), "dd/MM/yyyy"));
        return lc;
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewPhim.getModel();
        model.setRowCount(0);//clear table
        try {
            List<LichChieu> list = (List<LichChieu>) dao.selectByIdmaPhim(maPhim);
            for (LichChieu lc : list) {
                Object[] rows = {
                    lc.getMaLichChieu(),
//                    lc.getMaPhim(),
                    lc.getMaPhong(),
                    lc.getGioChieu(),
                    lc.getNgayChieu()
                };
                model.addRow(rows);
            }
//            LichChieu lc = dao.selectByIdmaPhim(maPhim);
//            if (lc != null) {
//                Object[] rows = {
//                    lc.getMaLichChieu(),
//                    lc.getMaPhim(),
//                    lc.getMaPhong(),
//                    lc.getGioChieu(),
//                    lc.getNgayChieu()
//                };
//                model.addRow(rows);
//            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu\n" + e);
        }

    }

//    void seach() {
//        HoaDon maPhim = new HoaDon();
//        LichChieu p = dao.selectByIdmaPhim(maPhim.getTenPhim());
//        if (p != null) {
//            txtMaLichChieu.setText(p.getMaLichChieu());
//            txtGioChieu.setText(p.getGioChieu());
//            txtMaPhong.setText(p.getMaPhong());
//            txtMaLichChieu.setText(p.getMaLichChieu());
//            txtNgayChieu.setText(XDate.toString(p.getNgayChieu(), "dd/MM/yyyy"));
//        }
//    }
    void find() {
        if (txtFind.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa nhập mã lịch chiếu");
        } else {
            LichChieu p = dao.selectById(txtFind.getText());
            if (p != null) {
                txtGioChieu.setText(p.getGioChieu());
                txtMaPhim.setText(p.getMaPhim());
                txtMaPhong.setText(p.getMaPhong());
                txtMaLichChieu.setText(p.getMaLichChieu());
                txtNgayChieu.setText(XDate.toString(p.getNgayChieu(), "dd/MM/yyyy"));
            }
        }
    }
}
